Replaced Buttons for Select Menu on scsearch
Ayeven/generic-bot pull request #7
Opened 2021-07-01 20:36 UTC by Murky-MoMo

This pr 

takes out the buttons for the command `scsearch` and implements it, and adds support for further select menu implementations 
(so instead of a <SlashCommand>.button method, it uses a `selectmenu` method)

few minor parts of the code were modified too,
like some variables were renamed to be more descriptive and
some _repetitive loops_ were removed

2021-07-01 20:38 UTC, Murky-MoMo commented
This also completes #6

2021-07-02 01:48 UTC, Ayeven requested changes
Line 32 of `scSearch.js` need extra param as I commented

2021-07-02 01:48 UTC, Ayeven commented on slash/music/scSearch.js
> +				customID: `${this.name}`,
If you notice on the `interaction` event file where I write `const SlashCommand = SlashCommands.get(SlashCommandName) || SlashCommands.get(CustomID.split('_')[0]);` This line will need `${this.name}_selectMenusName` Well, classic string split hack.

2021-07-02 01:48 UTC, Ayeven commented on slash/music/scSearch.js
> +						description: `${duration} | ${result[n].title}]`.slice(0, 48),
What does `.slice(0, 48)` do here?

2021-07-02 01:48 UTC, Ayeven commented on slash/music/scSearch.js
> +			const arrayResult = await scdl.search({ limit: 30, resourceType: 'tracks', query });
I just realized, I put in limit 15 on `run` method while in button/select menu is 30. My bad on that

2021-07-02 01:48 UTC, Ayeven commented on events/interaction.js
>  		const time = moment().format('YYYY MM DD HH:mm:ss');
Reviewing the code, I realize function `button` and `selectmenu` don't have them. so the `${time}` in both function is useless. Another oversight from me :kekw:

2021-07-02 06:40 UTC, Murky-MoMo commented on slash/music/scSearch.js
> +						description: `${duration} | ${result[n].title}]`.slice(0, 48),
https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-option-structure
select menu's description has a limit of 50 characters, so, to be safe, i cut the string down to 48 characters

2021-07-02 06:45 UTC, Murky-MoMo commented on slash/music/scSearch.js
> +				customID: `${this.name}`,
select menu doesn't work like buttons
each buttons have different `customID`s
and here, there's different `value`s on a single select menu, so there's no need to add anything here
if you ever user multiple select menus, then you may need to add different IDs for them, but for now, this is completely functional with just that

2021-07-02 06:49 UTC, Murky-MoMo commented on slash/music/scSearch.js
> +			const arrayResult = await scdl.search({ limit: 30, resourceType: 'tracks', query });
while converting the code, i didn't notice that, yeah it doesn't really change the outcome, but it's more consistent to fetch 15
I'll also have to mention how select menus have a max of 25 options available

2021-07-02 06:53 UTC, Murky-MoMo commented on events/interaction.js
>  		const time = moment().format('YYYY MM DD HH:mm:ss');
Sorry what?

2021-07-02 13:25 UTC, Ayeven commented on slash/music/scSearch.js
> +				customID: `${this.name}`,
I tried to test the PR, but met with no select menu pop up. Asked around on `discord.js` discord server, everything seem right, I even double check documentation.  This is all I got. Not sure what really happened. 
![image](https://user-images.githubusercontent.com/10782269/124281024-e71f9880-db7b-11eb-8472-a10cd313542e.png)

2021-07-02 13:29 UTC, Murky-MoMo commented on slash/music/scSearch.js
> +				customID: `${this.name}`,
we should honestly add a debug feature like how discord.js uses it
however, i'll redownload and test here, maybe your discord apps outdated
for now, console log the message, if you see the select menu in <Message>.components, then it's your discord

2021-07-02 13:37 UTC, Ayeven commented on slash/music/scSearch.js
> +				customID: `${this.name}`,
F! All it need is a restart of discord app, and the select menu appeared. The most wasted 2hrs of my time trying to figure something simple

2021-07-02 13:40 UTC, Murky-MoMo commented on slash/music/scSearch.js
> +				customID: `${this.name}`,
aha.. so it was your discord app as I said
well is there anything else you need clarification on?

2021-07-02 13:44 UTC, merged

2021-07-02 13:59 UTC, Murky-MoMo commented
> Line 32 of `scSearch.js` need extra param as I commented
yeah and I mentioned why it doesn't necessarily need it
the code works completely fine and since you're using a single component, which is the single select menu, it doesn't really need that
if you're using multiple components, then it'd be useful